### PR TITLE
sticky sidebar upon scroll

### PR DESCRIPTION
**Pull request by aaronranard**
This should sticky the sidebar when you begin scrolling. Please test various scenarios for me 🤞

### CODE REVIEW

**Comment by aaronranard** [comment]
I noticed the sidebar doesn't allow you to scroll within it now which is less than ideal, may be as simple as adding a container div like you mentioned earlier @jennyknuth

**Comment by jennyknuth** [comment]
^I was just playing with it and it felt pretty natural and usable to me. You'll have to show me a scenario that feels wrong to you, but so far, I like it!

**Comment by aaronranard** [comment]
@jennyknuth I added a sidebar-container class which makes the left nav scrollable. Give that a go and lmk your thoughts.

**Review by jennyknuth — COMMENTED** [review]
I like it!

**Pull request merged**
